### ISSUE TITLE
Search by breed, age, gender, availability, and date created

### ISSUE THREAD

**Issue by TeresitaCGNader** [senior-eng-project/Animal-Dating-App#26]
**Context**
When viewing the pet gallery, users should be able to filter the pet results by various inputs such as the breed, age, gender, availability, and creation date of the pet profile.

**Acceptance Criteria**
- [ ] A list of dropdown, button, or range selectors next to the text input search field for each filter category of:
  - [ ] Breed
  - [ ] Age
  - [ ] Gender
  - [ ] Availability
  - [ ] Creation Date

**Comment by stevenbertolucci** [comment]
Closed Task #26. I was able to fix the search bar functionality and the filter functionality as well. I created a list of filter check boxes except for Creation Date. It was not possible to retrieve the creation date from our database since it did not exist. Everything else is working beautifully and will attempt to make search bar and filter menu a component for v0.5
